In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3,)

In [8]:
b = np.array([[1,2,3],
                        [4,5,6]])

In [9]:
b.shape

(2, 3)

In [10]:
c1 = np.array([1,2,3,4,5,6])

In [11]:
c1.shape

(6,)

In [12]:
c2 = c1.reshape(2,3)

In [13]:
c2.shape

(2, 3)

In [14]:
print(c2)

[[1 2 3]
 [4 5 6]]


In [15]:
d = np.array([1,2,3], dtype=np.int16)

In [16]:
type(d)

numpy.ndarray

In [17]:
d

array([1, 2, 3], dtype=int16)

In [18]:
d.astype(np.float16)

array([1., 2., 3.], dtype=float16)

In [19]:
a[0]

1

In [20]:
a[1:]

array([2, 3])

In [21]:
b[0,[0,2]]

array([1, 3])